### ISSUE TITLE
Bug report / Feature requests

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#13]
_**ISSUE**_

1. Inside the Admin settings tab when you select `Users` you cannot invite other people to the panel, it's the same page as `Groups`.
2. Repealed Infractions cannot be deleted.

**_Feature requests_**
 1. Synchronization bans, a toggle option like this as example [https://i.imgur.com/4f6hLLO.png](url) + it would nice if it's displayed as well on the infractions logging system [https://i.imgur.com/oaNfVo7.png](url)
 2. Synchronization mutes, a toggle option like this as example [https://i.imgur.com/4f6hLLO.png](url) + it would nice if it's displayed as well on the infractions logging system [https://i.imgur.com/oaNfVo7.png](url) (picture of ban system)
 3. A system when you warn a person that his name in the playerlist turns yellow, when you kick the person and he joins back that it displays red color as name, and this with a customized ResetDuration when the name goes back to normal default colour.

**Comment by sniddunc** [comment]
Thanks for the bug reports. I'll release a patch soon with fixes.

I'm going to create an issue for each of the points you mentioned above and then reference back here for easier tracking. I'll respond to each of the feature requests in their corresponding issues.

**Comment by sniddunc** [comment]
The two bugs reported are fixed in Refractor-Svelte v0.2.1.

RefractorGSCM/Refractor-Svelte#13
RefractorGSCM/Refractor-Svelte#15

**Comment by sniddunc** [comment]
All features/bugs reported here have been resolved. Closing.
