### ISSUE TITLE
Issue inviting users

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#20]
The user failed to get invited, when recovering the account he is able to make further his account since then he receives a lost password / or verification mail. But the invites were never successful.

I ran `docker logs refractor -f` to gather you info.

`{"level":"error","ts":1636490677.537055,"caller":"api/errorhandler.go:69","msg":"An error occurred","error":"gomail: could not send email 1: 553 5.7.1 <refractor@smtp.titan.email>: Sender address rejected: not owned by user death@dukeofyork.org","stacktrace":"Refractor/pkg/api.GetEchoErrorHandler.func1\n\t/build/pkg/api/errorhandler.go:69\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/echo.go:647\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1929"}`

Thanks!

**Comment by sniddunc** [comment]
This is caused by Refractor auto-generating the sender address. I will add an environment variable to allow customization of the sender address. It will use the same SMTP From address which gets provided in the `quickstart.sh` script.

**Comment by sniddunc** [comment]
Fixed in release v0.2.1
