### ISSUE TITLE
Servers ID 

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#22]
When deleting a server and creating a new one it stacks up with server IDs, it does not re-use the old serverID that was created before. When deleting a server means also you can no longer see which old server he was banned from only the ID(does not really matter for me) but the main issue is when you look up Infraction Records is that you won't see the infractions in the list if you select an admin his username, only on the active servers which were never deleted.

**Comment by Deathay** [comment]
You no longer see the server name it shows up the ID which is no longer used [https://i.imgur.com/dqKfpS7.png](https://i.imgur.com/dqKfpS7.png) maybe it would be cool when you delete a server and add a new one that it uses that ID again and does not create a new one?

**Comment by sniddunc** [comment]
This is largely intended behavior. We cannot allow creation of a new server with the same ID or else that would violate the unique key constraints which our database schema uses. 

It sounds like there might be a possible bug in terms of being unable to search for records of deleted servers, though. I'll check into that at some point.

**Comment by Deathay** [comment]
Hey, I also noticed when moderating my servers that my server list is not in order like before, would be cool if you could choose how it keeps staying without moving down below all other servers.

**Comment by sniddunc** [comment]
@Deathay This is definitely something I can adresss. Please put it in a new ticket for tracking purposes, though.
