### ISSUE TITLE
kick/ban player in playerlist

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#23]
When banning, kicking, muting, warning a person the options stays in the user or be selected on a new user if you refresh the server list. When you kick, ban or the person leaves the server you have to refresh your page because you can no longer use these options on the other users, it bugs + playerlist can also no longer be refreshed. Maybe if you could test it out on your panel, it's quiete hard to explain or DM me on discord :D

**Comment by Deathay** [comment]
Ah don't mind the playerlist, i had to somehow reconnect it to rcon :D but still have to refresh the page each time i use a kick/ban command in playerlist

**Comment by sniddunc** [comment]
This does indeed sound like a bug. I'll look into it.

**Comment by sniddunc** [comment]
@Deathay are you talking about this kind of scenario?

1. You log a kick for a player from the server list
2. It executes a kick command and kicks them from the server
3. The player options box with the mute, warn, etc buttons stays open over a different player

Is that what you mean?

The player option staying open is a bug, but I'm still able to deselect them and select a different player afterwards to log another infraction. If this isn't the issue you ran into, please clarify. Thanks!

**Comment by sniddunc** [comment]
The issue I outlined above is fixed in the latest versions of Refractor and Refractor-Svelte. I'll keep this open until I get confirmation that the issue fixed was the issue you were referring to.

**Comment by Deathay** [comment]
> @Deathay are you talking about this kind of scenario?
> 
> 1. You log a kick for a player from the server list
> 2. It executes a kick command and kicks them from the server
> 3. The player options box with the mute, warn, etc buttons stays open over a different player
> 
> Is that what you mean?
> 
> The player option staying open is a bug, but I'm still able to deselect them and select a different player afterwards to log another infraction. If this isn't the issue you ran into, please clarify. Thanks!

Hi, you can not deselect the user if you have kicked/banned the person in the current version. Maybe it already fixed in the newer one you mentioned. I will definitely try out soon!

**Comment by Deathay** [comment]
Yep bug has been solved, thanks for the update!
