### ISSUE TITLE
Playerlist Name Display

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#33]
Hey,

When giving a player an infraction the name will be only colored if you refresh the page. Is it possible to make a live version playerlist like BattleMetrics? So that a person gets an infraction that the other user who uses Refractor sees that the name gets colored without refreshing the web page.

**Comment by sniddunc** [comment]
Yes, this is entire possible and was actually implemented in the previous iteration of Refractor.

This can be accomplished by sending infraction creation notifications over websockets to all connected clients. This could also allow all users to be notified when another user creates an infraction via a push notification or something.

I'll aim to have this implemented for v0.4.0.

**Comment by sniddunc** [comment]
Implemented in pre-release branch v0.4.0
