### ISSUE TITLE
Placeholder request

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#51]
Hey,

A place holder for Refractor admin names, so that if you punish a player he knows who punished him. You can for example use it for **{{PLAYER_NAME}} has been warned by {{ADMIN_NAME}}, reason: {{REASON}}.**

**Comment by sniddunc** [comment]
Good idea. I'll add this to the v0.5.0 milestone.

**Comment by sniddunc** [comment]
Implemented in branch v0.5.0
