### ISSUE TITLE
Playerlist

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#58]
Hey, 

sometimes the server is for example showing 27 players while there is 12 online. Also in the playerlist showing players that is not in the server, the only way to solve this is hitting the force refresh button, page refresh does not help, so only administrators are able to solve it for others that synced.

**Comment by sniddunc** [comment]
Yeah, it's meant to be an admin fixable thing. This is due to common server desyncs which exist in Mordhau.

This can definitely be remedied by adding a more extensive player queuing system, but I'm going to put this on the backlog for now as I've got a lot on my plate, currently.
