### ISSUE TITLE
Playerlist MC

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#60]
Players are not showing up in Mineraft servers. Also no records of users in database.

**Comment by sniddunc** [comment]
Have you followed the Minecraft install steps [here](https://refractor.dmas.dev/#/installation/minecraft?id=minecraft-server-setup)?

You need to have the RefractorMC plugin installed as it provides the needed player list command since the base playerlist commands do not include player UUIDs.

**Comment by Deathay** [comment]
Oh i did not, thanks for letting me know!
