### ISSUE TITLE
The initial user is not super admin after deploy

### ISSUE THREAD

**Issue by BattlefieldDuck** [RefractorGSCM/Refractor#9]
How to grant permissions to the first user? thank you.

**Comment by sniddunc** [comment]
It should have automatically granted super admin permissions to you. If this isn't the case, this is a bug.

You can use the postgres prompt to manually set your user's overrides to grant super admin permissions. Here are the steps:

1. Run the following command: `docker exec -it postgresd psql -U postgres`. Once in the prompt, continue to the next step.
2. Connect to the refractor database by typing `\c refractor`
3. Get your user's ID from the UserMeta table by entering the following SQL query and copying the returned ID. `select * from usermeta;`
4. Set your overrides in the UserOverrides table by running the following SQL query (replace YOUR_D with your account's UserID that you found in the last step): `insert into useroverrides (userid, allowoverrides) values ('YOUR_ID', '1');`
5. Exit the prompt with \q

You should have super admin privileges. If any of the above steps don't work, please let me know.

**Comment by BattlefieldDuck** [comment]
Thank you, it works! But the first step is `docker exec -it postgresd psql -U refractor` instead.

**Comment by sniddunc** [comment]
I'm going to re-open for visibility in-case anyone else runs into this issue.
